from model.contants import Contants
import os

class MatchModel:

    def getMatchListByDate(targetDate):
        matchList = []
        matchList.append(targetDate)
        matchList.append("dalian-ddd")
        matchList.append("guangzhou-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dsds-ddd")
        matchList.append("sss-ddd")
        matchList.append("aaa-ddd")
        matchList.append("dalian-ddd")
        matchList.append("guangzhou-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dsds-ddd")
        matchList.append("sss-ddd")
        matchList.append("aaa-ddd")
        matchList.append("dalian-ddd")
        matchList.append("guangzhou-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dsds-ddd")
        matchList.append("sss-ddd")
        matchList.append("aaa-ddd")
        matchList.append("dalian-ddd")
        matchList.append("guangzhou-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dsds-ddd")
        matchList.append("sss-ddd")
        matchList.append("aaa-ddd")
        matchList.append("dalian-ddd")
        matchList.append("guangzhou-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dsds-ddd")
        matchList.append("sss-ddd")
        matchList.append("aaa-ddd")
        matchList.append("dalian-ddd")
        matchList.append("guangzhou-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dsds-ddd")
        matchList.append("sss-ddd")
        matchList.append("aaa-ddd")
        matchList.append("dalian-ddd")
        matchList.append("guangzhou-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dsds-ddd")
        matchList.append("sss-ddd")
        matchList.append("aaa-ddd")
        matchList.append("dalian-ddd")
        matchList.append("guangzhou-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dsds-ddd")
        matchList.append("sss-ddd")
        matchList.append("aaa-ddd")
        matchList.append("dalian-ddd")
        matchList.append("guangzhou-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dalian-ddd")
        matchList.append("dsds-ddd")
        matchList.append("sss-ddd")
        matchList.append("aaa-ddd")
        return matchList